trigger:
- master

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- ${{ if and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')) }}:
  - template: verify.yml

- task: ShellScript@2
  inputs:
    scriptPath: generate.sh
  env:
    ACCESS_TOKEN: $(accesstoken)
    COMMIT_MESSAGE: $(Build.SourceVersionMessage)
    AKS_MANIFEST_REPO: $(destination_repo_url)
