trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: ShellScript@2
  inputs:
    scriptPath: generate.sh

- script: |
    echo "git push with token"
    git push https://$accesstoken@github.com/samiyaakhtar/aks-deploy-destination.git

