trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: ShellScript@2
  inputs:
    scriptPath: generate.sh
  env:
    ACCESS_TOKEN: $accesstoken

