trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: ShellScript@2
  inputs:
    scriptPath: build.sh

- powershell: |
   git --version
   git clone https://github.com/samiyaakhtar/aks-deploy-destination.git
   cd aks-deploy-destination
   git checkout master
   Write-Host "setup author info"
   git config user.email "me@samiya.ca"
   git config user.name "azure-pipelines[bot]"
   Write-Host "git commit with message"
   git commit --allow-empty -a -m "Updating yaml files as a test - Azure DevOps"
   git remote set-url origin git@github.com:samiyaakhtar/aks-deploy-destination.git
   Write-Host "git push"
   git push https://$(accesstoken)@github.com/samiyaakhtar/aks-deploy-destination.git
